title: Minh Anderson
author: Minh Anderson
email: minhanderson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Site Starter Materialize Templates for Jekyll

twitter_username: 
github_username:  mander101

sass:
    style: compressed

theme: jekyll-theme-modernist